#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
name: "Mike_Dopp"
description: "Fancy Pants"
language: "en"

url: https://mikedopp.github.io
baseurl: ''

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 5
#paginate_path: /page-:num
permalink: /:categories/:year/:month/:day/:title/

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------
#disqus-id: yourusername

enable-share: true
twitter: mikedopp
github: mikedopp
google: +mikedopp
facebook: mikedopp
linkedin: m1k3d0pp

rss-feed-limit: 10
rss-show-full: false

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./_site
gems: ['jekyll-paginate']

sass:
    style: :compressed
    sass_dir: assets/css/